let tableBody=document.querySelector(".discounts .table tbody")
let discounts=[
    {
        id:"1",
        disc_code:"719",
        disc_name:"Upfront Discount ME 5%",
        validity_from:"02-03-2024",
        validity_to:"30-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"ME",
        supplier:"galileo",
        amount:"5%"
    },
    {
        id:"2",
        disc_code:"693",
        disc_name:"SEG EGY ALL AD 100LE Gal Sab RT",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"NOT IN",
        airline_code:"NP",
        supplier:"galileo,sabre",
        amount:"100"
    },
    {
        id:"3",
        disc_code:"692",
        disc_name:"SEG EGY ALL AD 50LE Gal Sab OW",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"NOT IN",
        airline_code:"NP",
        supplier:"galileo,sabre",
        amount:"50"
    },
    {
        id:"4",
        disc_code:"690",
        disc_name:"SEG EGY ALL AD 50LE IMPORT OW",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"NOT IN",
        airline_code:"NP",
        supplier:"galileo,sabre",
        amount:"50"
    },
    {
        id:"5",
        disc_code:"695",
        disc_name:"SEG EGY NP AD 80LE Sabre RT MC",
        validity_from:"	27-12-2023",
        validity_to:"30-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"NP",
        supplier:"galileo",
        amount:"80"
    },
    {
        id:"6",
        disc_code:"694",
        disc_name:"SEG EGY NP AD 40LE GALIMP Sabre OW",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"NP",
        supplier:"galileo",
        amount:"40"
    },
    {
        id:"7",
        disc_code:"800",
        disc_name:"Upfront Discount BG 7%",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"egypt,united arab emirates,saudi arabia",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"BG",
        supplier:"galileo,amadeus",
        amount:"7%"
    },
    {
        id:"8",
        disc_code:"790",
        disc_name:"Backend Discount PK 1%",
        validity_from:"22-12-2023",
        validity_to:"30-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"BK",
        supplier:"galileo,amadeus",
        amount:"1%"
    },
    {
        id:"9",
        disc_code:"720",
        disc_name:"Backend EGY Shura 130EGP PT",
        validity_from:"	27-12-2023",
        validity_to:"30-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"All",
        supplier:"shura tech",
        amount:"130"
    },
    {
        id:"10",
        disc_code:"718",
        disc_name:"Backend UAE Shura 20AED PT",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"All",
        supplier:"shura tech",
        amount:"20"
    },
    {
        id:"11",
        disc_code:"851",
        disc_name:"SEG Kuwait ALL PT 1.2 KWD Gal Sab OW",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"kuwait",
        branches:"WtKD",
        agencies:"All",
        rule:"IN",
        airline_code:"NP,EK",
        supplier:"galileo,sabre",
        amount:"1.2"
    },
    {
        id:"12",
        disc_code:"850",
        disc_name:"SEG Kuwait ALL PT 2.2 KWD Gal Sab RT",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"kuwait",
        branches:"WtKD",
        agencies:"All",
        rule:"IN",
        airline_code:"NP,EK",
        supplier:"galileo,sabre",
        amount:"2.2"
    },
    {
        id:"13",
        disc_code:"853",
        disc_name:"SEG LIBYA ALL PT 8USD GAL Sab RT",
        validity_from:"31-12-2023",
        validity_to:"30-12-2024",
        country:"libya",
        branches:"All",
        agencies:"All",
        rule:"NOT IN",
        airline_code:"NP",
        supplier:"galileo,sabre",
        amount:"8"
    },
    {
        id:"14",
        disc_code:"852",
        disc_name:"SEG LIBYA ALL PT 4USD Gal Sab OW",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"libya",
        branches:"All",
        agencies:"All",
        rule:"NOT IN",
        airline_code:"NP",
        supplier:"galileo,sabre",
        amount:"4"
    },
    {
        id:"15",
        disc_code:"854",
        disc_name:"SEG UAE ALL PT 14AED Gal Sab OW",
        validity_from:"26-12-2023",
        validity_to:"29-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"NOT IN",
        airline_code:"NP,PK,EK",
        supplier:"galileo,sabre",
        amount:"14"
    },
    {
        id:"16",
        disc_code:"878",
        disc_name:"SEG UAE Extra (AI EY GF PR SV) 8AED Gal Sab RT",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"AI,EY,GF,PR,SV,ET,BS",
        supplier:"galileo,sabre",
        amount:"8"
    },
    {
        id:"877",
        disc_code:"718",
        disc_name:"SEG UAE Extra (AI EY GF PR SV) 4AED Gal Sab OW",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"AI,EY,GF,PR,SV,ET,BS",
        supplier:"galileo,sabre",
        amount:"4"
    },
    {
        id:"18",
        disc_code:"887",
        disc_name:"SEG UAE ALL PT 28AED Gal Sab RT",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"PK",
        supplier:"galileo,sabre",
        amount:"28"
    },
    {
        id:"19",
        disc_code:"885",
        disc_name:"SEG UAE PK PT 22AED Gal Sab RT",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"PK",
        supplier:"galileo,sabre",
        amount:"22"
    },
    {
        id:"20",
        disc_code:"884",
        disc_name:"	SEG UAE PK PT 11AED Gal Sab OW",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"PK",
        supplier:"galileo,sabre",
        amount:"11"
    },
    {
        id:"21",
        disc_code:"957",
        disc_name:"SEG EGY MS&NP ALL PT 400LE GALIMP RT MC",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"MS,NP",
        supplier:"galileo",
        amount:"400"
    },
    {
        id:"25",
        disc_code:"935",
        disc_name:"SEG EGY ALL PT 500LE GalIMP RT",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"NOT IN",
        airline_code:"MS,SM,NP",
        supplier:"galileo",
        amount:"500"
    },
    {
        id:"26",
        disc_code:"934",
        disc_name:"SEG EGY ALL PT 250LE GalIMP OW",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"NOT IN",
        airline_code:"MS,SM,NP",
        supplier:"galileo",
        amount:"250"
    },
    {
        id:"27",
        disc_code:"930",
        disc_name:"SEG EGY ALL PT 500LE Gal RT",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"NOT IN",
        airline_code:"MS,SM,NP",
        supplier:"galileo",
        amount:"500"
    },
    {
        id:"28",
        disc_code:"951",
        disc_name:"Backend Discount BG2% UAE Market",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"dubai",
        agencies:"All",
        rule:"IN",
        airline_code:"BG",
        supplier:"galileo",
        amount:"2"
    },
    {
        id:"29",
        disc_code:"946",
        disc_name:"SEG LIBYA NP ELJAAPP PT 3USD GU GE S OW",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"libya",
        branches:"DubaiATM",
        agencies:"Ejaapp Portal LLC",
        rule:"IN",
        airline_code:"NP",
        supplier:"galileo,sabre",
        amount:"3"
    },
    {
        id:"30",
        disc_code:"944",
        disc_name:"SEG LIBYA NP ELJAAPP PT 6USD GU GE S RT MC",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"libya",
        branches:"DubaiATM",
        agencies:"Ejaapp Portal LLC",
        rule:"IN",
        airline_code:"NP",
        supplier:"galileo,sabre",
        amount:"6"
    },
    {
        id:"31",
        disc_code:"959",
        disc_name:"SEG KSA ALL ALL PT 11.25SAR GAL SAB OW",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"saudi arabia",
        branches:"wonder saudia",
        agencies:"All",
        rule:"IN",
        airline_code:"All",
        supplier:"galileo,sabre",
        amount:"11.25"
    },
    {
        id:"32",
        disc_code:"960",
        disc_name:"SEG KSA ALL ALL PT 22.5SAR GAL SAB RT MC",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"saudi arabia",
        branches:"wonder saudia",
        agencies:"All",
        rule:"IN",
        airline_code:"All",
        supplier:"galileo,sabre",
        amount:"22.5"
    },
    {
        id:"33",
        disc_code:"1007",
        disc_name:"SEG EGY KU ALL AD PT 300LE SABRE OW",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"KU",
        supplier:"galileo",
        amount:"300"
    },
    {
        id:"34",
        disc_code:"1004",
        disc_name:"SEG EGY WY ALL PT AD 300LE GAL GALIMP OW",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"WY",
        supplier:"galileo",
        amount:"300"
    },
    {
        id:"35",
        disc_code:"1005",
        disc_name:"SEG EGY WY ALL AD PT 600LE GAL IMPGAL RT",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"WY",
        supplier:"galileo",
        amount:"600"
    },
    {
        id:"36",
        disc_code:"1023",
        disc_name:"SEG UAE NOT IN NP PK EK ALL AD PT 28AED GAL RT MC",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"NP,PK,EK",
        supplier:"galileo",
        amount:"28"
    },
    {
        id:"37",
        disc_code:"1021",
        disc_name:"SEG UAE AI EY GF PR SV ALL 4AED UAEEGYGALIMP OW",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"AI,EY,GF,PR,SV",
        supplier:"galileo",
        amount:"4"
    },
    {
        id:"38",
        disc_code:"1022",
        disc_name:"SEG UAE AI EY GF PR SV ALL 8AED UAEEGYGALIMP RT MC",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"AI,EY,GF,PR,SV",
        supplier:"galileo",
        amount:"8"
    },
    {
        id:"39",
        disc_code:"1018",
        disc_name:"SEG UAE PK ALL AD PT 22AED GAL RT MC",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"PK",
        supplier:"galileo",
        amount:"22"
    },
    {
        id:"40",
        disc_code:"1017",
        disc_name:"SEG UAE PK ALL AD PT 11AED GAL OW",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"PK",
        supplier:"galileo",
        amount:"11"
    },
    {
        id:"41",
        disc_code:"1041",
        disc_name:"Upfront ALL AT ALL AD PT 5% IMPGAL",
        validity_from:"1-1-2024",
        validity_to:"30-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"All",
        supplier:"galileo",
        amount:"5%"
    },
    {
        id:"42",
        disc_code:"1025",
        disc_name:"SEG EGY NOT IN NP ALL AD 100EGP GAL RT MC",
        validity_from:"24-12-2023",
        validity_to:"30-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"NOT IN",
        airline_code:"NP",
        supplier:"galileo",
        amount:"100"
    },
    {
        id:"43",
        disc_code:"1042",
        disc_name:"Upfront ALL TK ALL AD PT 1% GALIMP AMAD",
        validity_from:"1-1-2024",
        validity_to:"30-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"TK",
        supplier:"galileo,amadeus",
        amount:"1%"
    },
    {
        id:"44",
        disc_code:"1037",
        disc_name:"Upfront ALL TK ALL AD PT 1% GAL AMAD",
        validity_from:"1-1-2024",
        validity_to:"30-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"TK",
        supplier:"galileo,amadeus",
        amount:"1%"
    },
    {
        id:"45",
        disc_code:"1033",
        disc_name:"SEG LIBYA NOT IN NP EK ALL AD PT 4USD GALIMP OW",
        validity_from:"31-12-2023",
        validity_to:"30-12-2024",
        country:"libya",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"NP,EK",
        supplier:"galileo",
        amount:"4"
    },
    {
        id:"46",
        disc_code:"1035",
        disc_name:"SEG LIBYA NOT IN NP EK AD PT 8USD GALIMP RT MC",
        validity_from:"31-12-2023",
        validity_to:"30-12-2024",
        country:"libya",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"NP,EK",
        supplier:"galileo",
        amount:"8"
    },
    {
        id:"47",
        disc_code:"1038",
        disc_name:"Upfront ALL AT ALL AD PT 5% GAL AMA",
        validity_from:"01-01-2024",
        validity_to:"30-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"AT",
        supplier:"galileo,amadeus",
        amount:"5%"
    },
    {
        id:"48",
        disc_code:"1024",
        disc_name:"SEG UAE NOT IN NP PK EK ALL AD PT 14AED GAL OW",
        validity_from:"27-12-2023",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"NOT IN",
        airline_code:"NP,PK,EK",
        supplier:"galileo",
        amount:"14"
    },
    {
        id:"49",
        disc_code:"1052",
        disc_name:"Upfront UAE BS ALL AD PT 7% UAEGAL UAEGALIMP",
        validity_from:"02-01-2024",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"BS",
        supplier:"galileo",
        amount:"7%"
    },
    {
        id:"50",
        disc_code:"1027",
        disc_name:"SEG UAE KC ALL AD PT 18AED GAL OW RT",
        validity_from:"28-12-2023",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"KC",
        supplier:"galileo",
        amount:"18"
    },
    {
        id:"51",
        disc_code:"1096",
        disc_name:"SEG EGY NOT IN SV ALL PT 250EGP KSAGAL OW",
        validity_from:"16-02-2024",
        validity_to:"30-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"NOT IN",
        airline_code:"SV",
        supplier:"galileo",
        amount:"250"
    },
    {
        id:"52",
        disc_code:"1098",
        disc_name:"Backend EGY SV ALL PT 140EGP KSAGAL OW",
        validity_from:"16-02-2024",
        validity_to:"30-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"SV",
        supplier:"galileo",
        amount:"140"
    },
    {
        id:"53",
        disc_code:"1099",
        disc_name:"Backend EGY SV ALL PT 280 EGPKSAGAL RT MC",
        validity_from:"16-02-2024",
        validity_to:"30-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"SV",
        supplier:"galileo",
        amount:"280"
    },
    {
        id:"54",
        disc_code:"1089",
        disc_name:"Upfront SAUDIA RJ ALL ALL 2BLACKOUT 5% KSAGAL",
        validity_from:"31-05-2024",
        validity_to:"30-12-2024",
        country:"egypt,united arab emirates,saudi arabia",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"RJ",
        supplier:"galileo",
        amount:"5%"
    },
    {
        id:"55",
        disc_code:"1084",
        disc_name:"Backend ALL QR ALL AD PT 2% GAL GALIMP",
        validity_from:"05-04-2024",
        validity_to:"30-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"QR",
        supplier:"galileo",
        amount:"2%"
    },
    {
        id:"56",
        disc_code:"1100",
        disc_name:"Upfront ALL TK ALL AD PT 6% GAL AMAD OW RT",
        validity_from:"17-02-2024",
        validity_to:"30-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"TK",
        supplier:"galileo,amadeus",
        amount:"6%"
    },
    {
        id:"57",
        disc_code:"1055",
        disc_name:"SEG UAE NP ALL AD PT 24AED GAL GALIMP SAB",
        validity_from:"03-01-2024",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"NP",
        supplier:"galileo,sabre",
        amount:"24"
    },
    {
        id:"58",
        disc_code:"1053",
        disc_name:"SEG UAE NP ALL AD PT 14AED GAL GALIMP SAB",
        validity_from:"03-01-2024",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"NP",
        supplier:"galileo,sabre",
        amount:"12"
    },
    {
        id:"59",
        disc_code:"1054",
        disc_name:"SEG UAE NP ALL AD PT 14AED UAEGAL UAEGALIMP OW",
        validity_from:"03-01-2024",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"NP",
        supplier:"galileo",
        amount:"14"
    },
    {
        id:"60",
        disc_code:"1056",
        disc_name:"SEG UAE NP ALL AD PT 28AED UAEGAL UAEGALIMP RT MC",
        validity_from:"03-01-2024",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"NP",
        supplier:"galileo",
        amount:"28"
    },
    {
        id:"61",
        disc_code:"1128",
        disc_name:"Backend MS 2% UAE Market",
        validity_from:"05-03-2024",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"MS",
        supplier:"galileo",
        amount:"2%"
    },
    {
        id:"62",
        disc_code:"1135",
        disc_name:"Upfront Discount BG 7% KSA",
        validity_from:"13-03-2024",
        validity_to:"30-12-2024",
        country:"egypt,united arab emirates,saudi arabia",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"BG",
        supplier:"galileo",
        amount:"7%"
    },
    {
        id:"63",
        disc_code:"1106",
        disc_name:"SEG EGY NOT IN SV ALL PT 500EGP KSAGAL RT MC",
        validity_from:"17-02-2024",
        validity_to:"30-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"NOT IN",
        airline_code:"SV",
        supplier:"galileo",
        amount:"500"
    },
    {
        id:"64",
        disc_code:"1102",
        disc_name:"Upfront SOTO ALL TK ALL AD PT 2% GAL AMAD OW RT",
        validity_from:"17-02-2024",
        validity_to:"30-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"TK",
        supplier:"galileo,amadeus",
        amount:"2%"
    },
    {
        id:"65",
        disc_code:"1101",
        disc_name:"Upfront ALL TK ALL AD PT 8% GAL AMAD OW RT",
        validity_from:"17-02-2024",
        validity_to:"30-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"TK",
        supplier:"galileo,amadeus",
        amount:"8%"
    },
    {
        id:"66",
        disc_code:"1149",
        disc_name:"SEG UAE MS AD PT 14AED GAL OW",
        validity_from:"17-03-2024",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"MS",
        supplier:"galileo",
        amount:"14"
    },
    {
        id:"67",
        disc_code:"1148",
        disc_name:"Backend Discount MS 1% UAE Market",
        validity_from:"17-03-2024",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"MS",
        supplier:"galileo",
        amount:"1%"
    },
    {
        id:"69",
        disc_code:"1125",
        disc_name:"SEG UAE Extra ET 18AED Oneway",
        validity_from:"04-03-2024",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"ET",
        supplier:"galileo",
        amount:"18"
    },
    {
        id:"70",
        disc_code:"1126",
        disc_name:"SEG UAE Extra ET 36AED Roundtrip",
        validity_from:"04-03-2024",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"ET",
        supplier:"galileo",
        amount:"36"
    },
    {
        id:"71",
        disc_code:"1161",
        disc_name:"Backend EGY AT AD PT 2%",
        validity_from:"01-05-2024",
        validity_to:"31-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"AT",
        supplier:"galileo,amadeus",
        amount:"2%"
    },
    {
        id:"72",
        disc_code:"1162",
        disc_name:"Backend EGY QR AD PT 3%",
        validity_from:"01-05-2024",
        validity_to:"31-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"QR",
        supplier:"galileo,amadeus",
        amount:"3%"
    },
    {
        id:"73",
        disc_code:"1159",
        disc_name:"Backend EGY KU AD PT 2%",
        validity_from:"01-05-2024",
        validity_to:"31-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"KU",
        supplier:"galileo,amadeus",
        amount:"2%"
    },
    {
        id:"74",
        disc_code:"1160",
        disc_name:"Backend EGY WY AD PT 2%",
        validity_from:"01-05-2024",
        validity_to:"31-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"WY",
        supplier:"galileo,amadeus",
        amount:"2%"
    },
    {
        id:"75",
        disc_code:"1158",
        disc_name:"backend EGY GF AD PT 3%",
        validity_from:"01-05-2024",
        validity_to:"31-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"َGF",
        supplier:"galileo,amadeus",
        amount:"3%"
    },
    {
        id:"76",
        disc_code:"1157",
        disc_name:"Backend EGY NP AD PT 3% OW",
        validity_from:"01-05-2024",
        validity_to:"31-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"NP",
        supplier:"galileo,amadeus",
        amount:"3%"
    },
    {
        id:"77",
        disc_code:"1154",
        disc_name:"6 L.E AIRCAIRO",
        validity_from:"01-05-2024",
        validity_to:"31-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"All",
        supplier:"air cairo",
        amount:"6"
    },
    {
        id:"78",
        disc_code:"1153",
        disc_name:"3% AIRCAIRO",
        validity_from:"01-05-2024",
        validity_to:"31-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"All",
        supplier:"air cairo",
        amount:"3%"
    },
    {
        id:"79",
        disc_code:"1155",
        disc_name:"Backend EGY NP ALL AD PT 2 % GAL KSA",
        validity_from:"23-03-2024",
        validity_to:"30-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"NP",
        supplier:"galileo",
        amount:"2%"
    },
    {
        id:"80",
        disc_code:"1150",
        disc_name:"SEG UAE MS AD PT 28AED RT MC",
        validity_from:"17-03-2024",
        validity_to:"30-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"MS",
        supplier:"galileo",
        amount:"28"
    },
    {
        id:"81",
        disc_code:"1220",
        disc_name:"UPFRONT ALL ET ALL AD PT 5% UAEGAL UAEAMAD",
        validity_from:"02-07-2024",
        validity_to:"31-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"ET",
        supplier:"galileo,amadeus",
        amount:"5%"
    },
    {
        id:"82",
        disc_code:"1221",
        disc_name:"SEG EGY ALL PT 250 LE G-EGY OW",
        validity_from:"02-07-2024",
        validity_to:"31-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"NOT IN",
        airline_code:"MS,NP,SM",
        supplier:"galileo",
        amount:"250"
    },
    {
        id:"83",
        disc_code:"1219",
        disc_name:"UPFRONT ALL ET ALL AD PT 3% UAEGAL UAEAMAD",
        validity_from:"02-07-2024",
        validity_to:"31-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"ET",
        supplier:"galileo,amadeus",
        amount:"3%"
    },
    {
        id:"84",
        disc_code:"1217",
        disc_name:"Backend SV 6% EGY Market - EGY IATA",
        validity_from:"02-07-2024",
        validity_to:"31-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"SV",
        supplier:"galileo,amadeus",
        amount:"6%"
    },
    {
        id:"85",
        disc_code:"1192",
        disc_name:"Upfront Airblu 1%",
        validity_from:"12-06-2024",
        validity_to:"31-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"All",
        supplier:"air blue",
        amount:"1%"
    },
    {
        id:"86",
        disc_code:"1187",
        disc_name:"Indogo 2% UAE",
        validity_from:"05-06-2024",
        validity_to:"31-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"All",
        supplier:"indgo",
        amount:"2%"
    },
    {
        id:"87",
        disc_code:"1183",
        disc_name:"Frontend EGY ET 2% AD PT",
        validity_from:"30-05-2024",
        validity_to:"31-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"ET",
        supplier:"galileo",
        amount:"2%"
    },
    {
        id:"88",
        disc_code:"1177",
        disc_name:"SEG EGY KU ALL AD PT 600LE SABRE RT",
        validity_from:"14-05-2024",
        validity_to:"31-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"KU",
        supplier:"galileo",
        amount:"600"
    },
    {
        id:"89",
        disc_code:"1181",
        disc_name:"KSA IMPORT 22.5 ON Galleio",
        validity_from:"28-05-2024",
        validity_to:"31-12-2024",
        country:"saudi arabia",
        branches:"wonder saudia",
        agencies:"All",
        rule:"IN",
        airline_code:"All",
        supplier:"galileo",
        amount:"22.5"
    },
    {
        id:"90",
        disc_code:"1182",
        disc_name:"KSA IMORT on Saudia 11.25",
        validity_from:"28-05-2024",
        validity_to:"31-12-2024",
        country:"saudi arabia",
        branches:"wonder saudia",
        agencies:"All",
        rule:"IN",
        airline_code:"All",
        supplier:"galileo",
        amount:"11.25"
    },
    {
        id:"92",
        disc_code:"1300",
        disc_name:"Backend FlyDubai 5%",
        validity_from:"24-07-2024",
        validity_to:"31-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"All",
        supplier:"flydubai",
        amount:"5%"
    },
    {
        id:"101",
        disc_code:"1334",
        disc_name:"SEG EGY MS ALL PT 200LE AMAD OW Branch",
        validity_from:"02-08-2024",
        validity_to:"31-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"MS",
        supplier:"amadeus",
        amount:"200"
    },
    {
        id:"102",
        disc_code:"1333",
        disc_name:"SEG EGY NP ALL PT 400LE AMAD BRANCH",
        validity_from:"02-08-2024",
        validity_to:"31-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"NP",
        supplier:"amadeus",
        amount:"400"
    },
    {
        id:"103",
        disc_code:"1332",
        disc_name:"SEG EGY MS ALL PT 400 AMAD Branch",
        validity_from:"02-08-2024",
        validity_to:"31-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"MS",
        supplier:"amadeus",
        amount:"400"
    },
    {
        id:"104",
        disc_code:"1328",
        disc_name:"SEG EGY MS ALL PT 200LE AMAD OW",
        validity_from:"02-08-2024",
        validity_to:"31-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"MS",
        supplier:"amadeus",
        amount:"200"
    },
    {
        id:"105",
        disc_code:"1326",
        disc_name:"SEC EGY MS ALL PT 400 AMAD",
        validity_from:"02-08-2024",
        validity_to:"31-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"MS",
        supplier:"amadeus",
        amount:"400"
    },
    {
        id:"106",
        disc_code:"1329",
        disc_name:"SEC EGY NP ALL PT 200LE AMAD OW",
        validity_from:"02-08-2024",
        validity_to:"31-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"NP",
        supplier:"amadeus",
        amount:"200"
    },
    {
        id:"107",
        disc_code:"1383",
        disc_name:"SEG EGY GF 250 EGP PT OW",
        validity_from:"19-08-2024",
        validity_to:"31-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"GF",
        supplier:"galileo",
        amount:"250"
    },
    {
        id:"108",
        disc_code:"1382",
        disc_name:"Backend KU 5% EGY Market",
        validity_from:"18-08-2024",
        validity_to:"31-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"KU",
        supplier:"galileo",
        amount:"5%"
    },
    {
        id:"109",
        disc_code:"1381",
        disc_name:"SEG GF EGY 500 EGP PT RT MC",
        validity_from:"18-08-2024",
        validity_to:"31-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"GF",
        supplier:"galileo",
        amount:"500"
    },
    {
        id:"110",
        disc_code:"1379",
        disc_name:"SEG MS KSA 22.5 PT AMAD RT-MC",
        validity_from:"18-08-2024",
        validity_to:"31-12-2024",
        country:"saudi arabia",
        branches:"wonder saudia",
        agencies:"All",
        rule:"IN",
        airline_code:"MS",
        supplier:"amadeus",
        amount:"22.5"
    },
    {
        id:"111",
        disc_code:"1378",
        disc_name:"SEG MS KSA 11.25 PT AMAD EG OW",
        validity_from:"18-08-2024",
        validity_to:"31-12-2024",
        country:"saudi arabia",
        branches:"wonder saudia",
        agencies:"All",
        rule:"IN",
        airline_code:"MS",
        supplier:"amadeus",
        amount:"11.25"
    },
    {
        id:"112",
        disc_code:"1377",
        disc_name:"SEG NP KSA 22.5 PT AMAD RT-MC",
        validity_from:"18-08-2024",
        validity_to:"31-12-2024",
        country:"saudi arabia",
        branches:"wonder saudia",
        agencies:"All",
        rule:"IN",
        airline_code:"NP",
        supplier:"amadeus",
        amount:"22.5"
    },
    {
        id:"113",
        disc_code:"1376",
        disc_name:"SEG NP KSA 11.25 PT AMAD OW",
        validity_from:"18-08-2024",
        validity_to:"31-12-2024",
        country:"saudi arabia",
        branches:"wonder saudia",
        agencies:"All",
        rule:"IN",
        airline_code:"NP",
        supplier:"amadeus",
        amount:"11.25"
    },
    {
        id:"114",
        disc_code:"1371",
        disc_name:"US - Bangla 7% KSA (G-A) P",
        validity_from:"15-08-2024",
        validity_to:"31-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"BS",
        supplier:"galileo,amadeus",
        amount:"7%"
    },
    {
        id:"115",
        disc_code:"1370",
        disc_name:"(SM) UAE Test 0",
        validity_from:"15-08-2024",
        validity_to:"31-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"All",
        supplier:"aircairouae",
        amount:"0"
    },
    {
        id:"116",
        disc_code:"1367",
        disc_name:"(SM) All Test",
        validity_from:"15-08-2024",
        validity_to:"31-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"All",
        supplier:"aircairouae",
        amount:"0"
    },
    {
        id:"118",
        disc_code:"1400",
        disc_name:"Backend SV All Markets 2.5%",
        validity_from:"05-09-2024",
        validity_to:"31-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"SV",
        supplier:"galileo",
        amount:"2.5%"
    },
    {
        id:"119",
        disc_code:"1398",
        disc_name:"Upfront SM UAE 5%",
        validity_from:"02-09-2024",
        validity_to:"31-12-2024",
        country:"All",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"SM",
        supplier:"amadeus",
        amount:"5%"
    },
    {
        id:"120",
        disc_code:"1384",
        disc_name:"SEC EGY NP ALL PT 200LE Galileo OW import",
        validity_from:"02-08-2024",
        validity_to:"31-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"NP",
        supplier:"galileo",
        amount:"200"
    },
    {
        id:"121",
        disc_code:"1385",
        disc_name:"SEG EGY NP ALL PT 400LE Galileo Import",
        validity_from:"02-08-2024",
        validity_to:"31-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"NP",
        supplier:"galileo",
        amount:"400"
    },
    {
        id:"122",
        disc_code:"1386",
        disc_name:"Segment EK KSA OW IATA UAE Market",
        validity_from:"21-08-2024",
        validity_to:"31-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"EK",
        supplier:"galileo",
        amount:"14"
    },
    {
        id:"123",
        disc_code:"1387",
        disc_name:"Segment EK KSA IATA RT UAE Market",
        validity_from:"21-08-2024",
        validity_to:"31-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"EK",
        supplier:"galileo",
        amount:"28"
    },
    {
        id:"124",
        disc_code:"1388",
        disc_name:"Backend EK KSA IATA UAE Market",
        validity_from:"21-08-2024",
        validity_to:"31-12-2024",
        country:"united arab emirates",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"EK",
        supplier:"galileo",
        amount:"2%"
    },
    {
        id:"125",
        disc_code:"958",
        disc_name:"SEG EGY MS ALL PT 200LE GALIMP OW",
        validity_from:"08-08-2024",
        validity_to:"31-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"MS",
        supplier:"galileo",
        amount:"200"
    },
    {
        id:"126",
        disc_code:"1323",
        disc_name:"Backend KWIJAZ DIS MARKT EGY Upper EGY Branches",
        validity_from:"23-07-2024",
        validity_to:"31-12-2024",
        country:"egypt",
        branches:"Sohag,Qena,Minia,Bani Seuf",
        agencies:"All",
        rule:"IN",
        airline_code:"All",
        supplier:"jazeeraairwayskwi",
        amount:"3%"
    },
    {
        id:"127",
        disc_code:"1324",
        disc_name:"Back End HMB ATZ LXR - KWI J9 KU",
        validity_from:"01-08-2024",
        validity_to:"31-12-2024",
        country:"egypt",
        branches:"All",
        agencies:"All",
        rule:"IN",
        airline_code:"All",
        supplier:"jazeeraairwayskwi",
        amount:"3%"
    },
    {
        id:"128",
        disc_code:"1366",
        disc_name:"(SV) AGN3724 AGN524 Extra 60 EGP",
        validity_from:"13-08-2024",
        validity_to:"31-12-2024",
        country:"egypt",
        branches:"Menoufia,Minia",
        agencies:"romatravel el awqaf,A-mariano travelsheben",
        rule:"IN",
        airline_code:"SV",
        supplier:"galileo,amadeus",
        amount:"60"
    },
    

    

]
console.log(discounts.length)
function draw(discounts){
    let discount=discounts.map((item)=>{
        return `
        <tr>
        <td>${item.disc_code}</td>
        <td>${item.disc_name}</td>
        <td>${item.validity_from}</td>
        <td>${item.validity_to}</td>
        <td class="country">${item.country}</td>
        <td>${item.branches}</td>
        <td>${item.agencies}</td>
        <td>${item.rule} ${item.airline_code}</td>
        <td class="supplier">${item.supplier}</td>
        <td>${item.amount}</td>
        </tr>

        `;
    })
    tableBody.innerHTML=discount.join('')

}
function calctotal(discounts){
    const totalDiscounts=document.querySelector(".total")
    totalDiscounts.innerHTML=`Total Discounts: ${discounts.length}`
    return totalDiscounts
}
draw(discounts)
calctotal(discounts)
/*/////////             search           ///////////////////////*/
let searchSelect=document.querySelector("#search-select")
let searchInput=document.querySelector("#search-input")
searchInput.addEventListener("input",function(){
    if(searchInput.value!==""){
        if(searchSelect.value=="airline"){
            searchInput.maxLength="2"
            let discount=discounts.filter((item)=>(item.rule=="IN" && item.airline_code.includes(searchInput.value.toUpperCase())) || (item.rule=="IN" && item.airline_code=="All") || (item.rule=="NOT IN" && !item.airline_code.includes(searchInput.value.toUpperCase())))
            draw(discount)
            calctotal(discount)
        }
        else if(searchSelect.value=="supplier"){
            searchInput.maxLength="20"
            let discount=discounts.filter((item)=>item.supplier.includes(searchInput.value.toLowerCase()))
            draw(discount)
            calctotal(discount)

        }
        else if(searchSelect.value=="market"){
            searchInput.maxLength="20"
            let discount=discounts.filter((item)=>(item.country.includes(searchInput.value.toLowerCase()))||(item.country=="All"))
            draw(discount)
            calctotal(discount)
        }
    }
    else{
        draw(discounts)
        calctotal(discounts)
    }

})
